LIDE-52 ajout des fichiers http-config.js et task-service.je pour axi…
ua-lide-dev/LIDE-APP pull request #17
Opened 2020-11-13 10:42 UTC by maxtess49

…os + appel avec axios des routes backend

2020-11-13 11:21 UTC, AloisL commented on lide-web/src/services/task-service.js
> +
On a retravaillé un peu les routes hier, on a décidé d'identifier les utilisateurs / projets / fichiers par leur nom plutôt que leur id, il faudrait refactor toutes les requêtes pour prendre en compte ce changement. 

Pour rappel, un nom d'utilisateur univ angers est forcément unique , un nom de projet est unique et un nom de fichier est unique au sein d'un projet. Ca serait redondant d'ajouter un id.

2020-11-13 11:30 UTC, AloisL commented on lide-web/src/services/task-service.js
> +
Il faudrait que le username soit passé dans le header de la requête plutot que dans l'url (en paramètres en quelques sortes).

Pour ce qui concerne le chemin d'accès du projet / fichier  et le contenu d'un fichier, l'idée serait de passer le contenu dans le body de la requête.

Pareil si ce n'est pas clair, n'hésite pas à poser des questions.

2020-11-13 11:37 UTC, AloisL commented on lide-web/src/services/task-service.js
> +  return http.get("/user/" + idUser + "/project");
exemple ici ->

function getProjects(username) {
    http.setHeader("username", username)
    return http.get("/getUserProjects");
}

2020-11-13 11:37 UTC, AloisL commented on lide-web/src/services/task-service.js
> +function getProjects(idUser) {
exemple ici ->

function getProjects(username) {
http.setHeader("username", username)
return http.get("/getUserProjects");
}

2020-11-13 11:47 UTC, AloisL requested changes
cf commentaires eplicatifs dans le code

2020-11-16 13:20 UTC, ThibaudViret approved these changes

2020-11-16 13:21 UTC, merged